### ISSUE TITLE
Room renderer crashes when loading Gorea_Land without players

### ISSUE THREAD

**Issue by AlaryVanEeckhout** [NoneGiven/MphRead#118]
Hi, I am on Windows 11 and I downloaded the 0.23.3.0 win version of MphRead.
I drag-and-dropped the AMHE1 version of Metroid Prime Hunters into the program to extract the game files.

Launching room 89(Gorea_Land) without players will make the program crash with this error:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at MphRead.Entities.PlayerEntity.CloseDialogs() in D:\mph_build\MphRead\Entities\Players\PlayerDialog.cs:line 414
   at MphRead.Formats.CameraSequence.SetUp(CameraInfo camInfo, UInt16 transitionTime) in D:\mph_build\MphRead\Entities\CamSeq\CameraSequence.cs:line 220
   at MphRead.Entities.CamSeqEntity.Start() in D:\mph_build\MphRead\Entities\CamSeq\CamSeqEntity.cs:line 202
   at MphRead.Entities.CamSeqEntity.TryStart() in D:\mph_build\MphRead\Entities\CamSeq\CamSeqEntity.cs:line 179
   at MphRead.Entities.CamSeqEntity.Process() in D:\mph_build\MphRead\Entities\CamSeq\CamSeqEntity.cs:line 82
   at MphRead.Scene.UpdateScene() in D:\mph_build\MphRead\Renderer.cs:line 2607
   at MphRead.Scene.OnUpdateFrame() in D:\mph_build\MphRead\Renderer.cs:line 1144
   at MphRead.RenderWindow.OnRenderFrame(FrameEventArgs args) in D:\mph_build\MphRead\Renderer.cs:line 4741
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at MphRead.Menu.ShowMenuPrompts() in D:\mph_build\MphRead\Menu.cs:line 712
   at MphRead.Program.Main(String[] args) in D:\mph_build\MphRead\Program.cs:line 28
```
This is the only room that I know of that causes a crash on this version.

**Comment by NoneGiven** [comment]
Fixed in 0.23.4.0
