### ISSUE TITLE
Error Loading model with blender script

### ISSUE THREAD

**Issue by Sir-LoLz** [NoneGiven/MphRead#123]
I am not able to import the samus model correctly.
`Python: Traceback (most recent call last):
  File "\import_Samus_lod0.py", line 11871, in <module>
  File "\import_Samus_lod0.py", line 19, in import_dae
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mph_common.py", line 83, in set_common
    set_vertex_colors(material)
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mph_common.py", line 93, in set_vertex_colors
    material.link_nodes(
  File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mph_common.py", line 55, in material_link_nodes
    source.outputs[output],
AttributeError: 'NoneType' object has no attribute 'outputs'`

**Comment by NoneGiven** [comment]
When submitting a bug report, please provide information like which version of MphRead you're using. In this case it would be relevant both what version you exported the model with, and what version the `mph_common.py` script came from, if different.

Inferring from the stack trace, I believe you're using 0.22.0.0. If so, update to the most recent version of MphRead and replace the `mph_common.py` script with the one from that version as well. It should fix the issue.

**Comment by Sir-LoLz** [comment]
Apologies for the lack of information.

You are correct. After updating to the latest build it works fine now.
