### ISSUE TITLE
Can't find scanlog

### ISSUE THREAD

**Issue by sotogami** [NoneGiven/MphRead#126]
```
#MphRead Version 0.25.0.0

Loading...
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\mph\files\AMHK0\stringTables\ScanLog.bin'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at MphRead.Text.Strings.ReadStringTable(String name, Language language) in D:\mph_build\MphRead\Strings.cs:line 23
   at MphRead.Text.Strings.GetEntry(Char type, UInt32 id, String table, Language language) in D:\mph_build\MphRead\Strings.cs:line 103
   at MphRead.Text.Strings.GetScanEntryCategory(Int32 scanId) in D:\mph_build\MphRead\Strings.cs:line 146
   at MphRead.StorySave.UpdateLogbook(Int32 scanId) in D:\mph_build\MphRead\GameState.cs:line 1488
   at MphRead.StorySave..ctor() in D:\mph_build\MphRead\GameState.cs:line 1347
   at MphRead.GameState.Reset() in D:\mph_build\MphRead\GameState.cs:line 1247
   at MphRead.Scene..ctor(Vector2i size, KeyboardState keyboardState, MouseState mouseState, Action`1 setTitle, Action close) in D:\mph_build\MphRead\Renderer.cs:line 218
   at MphRead.RenderWindow..ctor() in D:\mph_build\MphRead\Renderer.cs:line 4701
   at MphRead.Menu.ShowMenuPrompts() in D:\mph_build\MphRead\Menu.cs:line 708
   at MphRead.Program.Main(String[] args) in D:\mph_build\MphRead\Program.cs:line 28

```

Hello, I put in the Korean version of ROM and it gets this error, how do I solve it?

**Comment by NoneGiven** [comment]
You could work around the issue by renaming the `stringTables_jp` folder to just `stringTables`. However, loading the Korean (or Japanese) language files is not supported, so all the text will display as question marks.

I'll see about adding language support soon.

**Comment by NoneGiven** [comment]
This is fixed in 0.26.0.0.
