### ISSUE TITLE
MphRead not finding the room/model

### ISSUE THREAD

**Issue by Kicool-Grumm** [NoneGiven/MphRead#80]
Hey, maybe I'm dumb, I don't use a lot of softwares through prompt.
But I'm running through a problem. I have extracted the 0.16.1.0 release, and extracted the ROM's files by dragging it on the executable.
Now when I run a command prompt, I encounter this code error:
```
C:\Users\ShrekitoBoy\Downloads\Softwares\Games\ROMS\Nintendo DS - nds\MphRead-0.16.1.0-win>MphRead -room TeleportRoom
Unhandled exception. MphRead.ProgramException: No room with this name is known.
   at MphRead.SceneSetup.LoadRoom(String name, GameMode mode, Int32 playerCount, BossFlags bossFlags, Int32 nodeLayerMask, Int32 entityLayerId, Scene scene) in D:\mph_build\MphRead\SceneSetup.cs:line 23
   at MphRead.Scene.AddRoom(String name, GameMode mode, Int32 playerCount, BossFlags bossFlags, Int32 nodeLayerMask, Int32 entityLayerId) in D:\mph_build\MphRead\Renderer.cs:line 179
   at MphRead.Program.Main(String[] args) in D:\mph_build\MphRead\Program.cs:line 109
```
Would you know how to fix this? I don't have a D: directory yet it looks in there for the room.

Thanks in advance! Your work is really awesome, man.

**Comment by NoneGiven** [comment]
It's not looking in `D:`, that's just a source code path. The problem is that there's no room called "TeleportRoom". The names you want can be found in [this list](https://github.com/NoneGiven/MphRead/wiki/Rooms), in the Name column. For the boss teleporter room that would be UNIT1_TP1, UNIT1_TP2, etc.

**Comment by Kicool-Grumm** [comment]
Oh okay. But it brings another issue. Apparently some parts are missing? Here's the log.
```
C:\Users\ShrekitoBoy\Downloads\Softwares\Games\ROMS\Nintendo DS - nds\MphRead-0.16.1.0-win>MphRead -room UNIT1_TP1
Unhandled exception. System.IO.IOException: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte. : 'C:\Users\ShrekitoBoy\Downloads\Softwares\Games\ROMS\Nintendo DS - nds\MphRead-0.16.1.0-win\"C:\Users\ShrekitoBoy\Downloads\Softwares\Games\ROMS\Nintendo DS - nds\MphRead-0.16.1.0-win\files\mph"\"C:\Users\ShrekitoBoy\Downloads\Softwares\Games\ROMS\Nintendo DS - nds\MphRead-0.16.1.0-win\files\mph"\levels\entities\Unit1_TP1_Ent.bin'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.ReadAllBytes(String path)
   at MphRead.Read.ReadBytes(String path, Boolean firstHunt) in D:\mph_build\MphRead\Read.cs:line 540
   at MphRead.Read.GetEntities(String path, Int32 layerId, Boolean firstHunt) in D:\mph_build\MphRead\Read.cs:line 639
   at MphRead.SceneSetup.LoadEntities(RoomMetadata metadata, Int32 areaId, Int32 layerId, GameMode mode) in D:\mph_build\MphRead\SceneSetup.cs:line 220
   at MphRead.SceneSetup.LoadRoom(String name, GameMode mode, Int32 playerCount, BossFlags bossFlags, Int32 nodeLayerMask, Int32 entityLayerId, Scene scene) in D:\mph_build\MphRead\SceneSetup.cs:line 55
   at MphRead.Scene.AddRoom(String name, GameMode mode, Int32 playerCount, BossFlags bossFlags, Int32 nodeLayerMask, Int32 entityLayerId) in D:\mph_build\MphRead\Renderer.cs:line 179
   at MphRead.Program.Main(String[] args) in D:\mph_build\MphRead\Program.cs:line 109
```
It did the same thing before when I tried with the correct names, so that's why I had tried "TeleportRoom".

**Comment by Kicool-Grumm** [comment]
Oh okay. But it brings another issue. Apparently some parts are missing? Here's the log.
```
C:\Users\ShrekitoBoy\Downloads\Softwares\Games\ROMS\Nintendo DS - nds\MphRead-0.16.1.0-win>MphRead -room UNIT1_TP1
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ShrekitoBoy\Downloads\Softwares\Games\ROMS\Nintendo DS - nds\MphRead-0.16.1.0-win\files\mph\files\mph\levels\entities\Unit1_TP1_Ent.bin'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.ReadAllBytes(String path)
   at MphRead.Read.ReadBytes(String path, Boolean firstHunt) in D:\mph_build\MphRead\Read.cs:line 540
   at MphRead.Read.GetEntities(String path, Int32 layerId, Boolean firstHunt) in D:\mph_build\MphRead\Read.cs:line 639
   at MphRead.SceneSetup.LoadEntities(RoomMetadata metadata, Int32 areaId, Int32 layerId, GameMode mode) in D:\mph_build\MphRead\SceneSetup.cs:line 220
   at MphRead.SceneSetup.LoadRoom(String name, GameMode mode, Int32 playerCount, BossFlags bossFlags, Int32 nodeLayerMask, Int32 entityLayerId, Scene scene) in D:\mph_build\MphRead\SceneSetup.cs:line 55
   at MphRead.Scene.AddRoom(String name, GameMode mode, Int32 playerCount, BossFlags bossFlags, Int32 nodeLayerMask, Int32 entityLayerId) in D:\mph_build\MphRead\Renderer.cs:line 179
   at MphRead.Program.Main(String[] args) in D:\mph_build\MphRead\Program.cs:line 109
```
It did the same thing before when I tried with the correct names, so that's why I had tried "TeleportRoom".

**Comment by NoneGiven** [comment]
The two paths you posted aren't the same. One has `files\mph\files\mph\levels` and the other `files\mph\levels`. Check the `paths.txt` file in the MphRead directory and make sure the first line has the correct path.

**Comment by Kicool-Grumm** [comment]
Yes I also saw this but I don't understand, because the paths.txt only contains:
`files\mph

`

**Comment by Kicool-Grumm** [comment]
Okay I tried copying all that was inside files\mph to files\mph\files\mph by creating a new folder, and now it works. I'm astounded by the quality of the renders. Thanks a lot!

**Comment by NoneGiven** [comment]
>Yes I also saw this but I don't understand, because the paths.txt only contains:
>`files\mph

Sounds like a bug where the setup process puts a relative path in `paths.txt` instead of an absolute path. I'll fix that in the next release. Glad you got it working though.
